language: c
cache:
  directories:
      - "$HOME/.cache"
      - "$HOME/.ccache"
before_install:
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    - wget https://package-data.enthought.com/edm/rh5_x86_64/1.4/edm_1.4.1_linux_x86_64.sh && bash ./edm_1.4.1_linux_x86_64.sh -b -p $HOME
    - export PATH=${HOME}/edm/bin:${PATH}
    - edm environments create simphony
    - . $HOME/.edm/envs/simphony/bin/activate 
    - edm install -y pip setuptools pyqt 
install:
    - pip install -r requirements.txt
    - python setup.py develop
script:
    - pip install -r dev_requirements.txt
    - flake8 .
    - python -m unittest discover
    - pip install -r doc_requirements.txt
    - sphinx-build -W doc/source doc/build/sphinx
after_success:
    - codecov
